name: "alist-TvBox"
description: "AList代理，支持界面管理。"
version: "latest"
slug: "alist-tvbox"
url: https://github.com/power721/alist-tvbox
image:  haroldli/xiaoya-tvbox
init: false
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:4567]"
ports:
  4567/tcp: 4567
  80/tcp: 5344
environment:
  no_proxy: "*.aliyundrive.com"
  ALIST_PORT: "5344"
  INSTALL: "xiaoya"
  MEM_OPT: "-Xmx512M"
boot: manual
