name: "FRP客户端自定义配置版"
description: "网页配置页直接粘贴frpc.toml，支持启动/重启与看门狗自动拉起"
version: "0.59.0-4"
slug: "frp_client_zdy"
host_network: true
startup: application
boot: "auto"
init: false
ingress: true
ingress_port: 8080
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

