name: "FRP客户端自定义配置版"
description: "支持多类型多配置的frp加载项"
version: "1.0.3"
slug: "frp_client_zdy"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

