name: "FRP客户端自定义配置版"
description: "网页配置frpc.toml，在线下载/切换frp版本（支持镜像加速），看门狗自动拉起"
version: "1.0.0"
slug: "frp_client_zdy"
host_network: true
startup: application
boot: "auto"
init: false
ingress: true
ingress_port: 8080
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

